# Generated by Django 4.0 on 2022-08-18 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_jobrole_partno_supplier_unit_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141650)),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141638)),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141958)),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141867)),
        ),
        migrations.AlterField(
            model_name='partno',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 140601)),
        ),
        migrations.AlterField(
            model_name='partno',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 140578)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 143728)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 143712)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141393)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 141376)),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 144552)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 140988)),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 140973)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 143138)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 7, 33, 57, 143093)),
        ),
    ]
